# Generated by Django 5.1.1 on 2024-11-10 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='the title of the article', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True, help_text='the user id who scored')),
                ('score', models.PositiveSmallIntegerField(help_text='the score that can be between 1 to 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_suspicious', models.BooleanField(default=False, help_text='the score can be suspicious based on user activity')),
                ('article', models.ForeignKey(help_text='score related to an article', on_delete=django.db.models.deletion.DO_NOTHING, to='article.article')),
            ],
        ),
    ]
